name: Unique Sessions
description: Number of distinct user sessions that have made a query.
tableName: clearcare_queries
updatedAt: "2026-02-21T00:00:00.000Z"
metricQuery:
  exploreName: clearcare_queries
  dimensions: []
  metrics:
    - clearcare_queries_unique_sessions
  filters: {}
  sorts: []
  limit: 1
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    selectedField: clearcare_queries_unique_sessions
    label: Unique Sessions
    showBigNumberLabel: true
slug: unique-sessions-kpi
spaceSlug: shared
version: 1
